ffe/urls.py
from django.urls import path

from . import views
from .views import add_recipe, recipe_detail, add_comment, toggle_favorite, user_detail, delete_recipe

urlpatterns = [

    path("", views.homepage, name="homepage"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="my-login"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("user_logout/", views.user_logout, name="user_logout"),
    path('explore/', views.explore, name='explore'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/<int:recipe_id>/add_comment/', add_comment, name='add_comment'),
    path('toggle_favorite/<int:recipe_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('favorites/', views.favorites, name='favorites'),
    path('favorites/<int:recipe_id>/remove/', views.remove_favorite, name='remove_favorite'),
    path('search/', views.search, name='search'),
    path('category/<str:category>/', views.category_recipes, name='category_recipes'),
    path('follow_user/<str:username>/', views.follow_user, name='follow_user'),
    path('unfollow_user/<str:username>/', views.unfollow_user, name='unfollow_user'),
    path('user/<str:username>/', user_detail, name='user_detail'),
    path('profile/', views.profile, name='profile'),
    path('add-recipe/', views.add_recipe, name='add_recipe'),
    path('change_password/', views.change_password, name='change_password'),
    path('recipe/<int:recipe_id>/delete/', delete_recipe, name='delete_recipe'),
    path('edit_recipe/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ffe.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ffe/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.db import models


class Recipe(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='authored_recipes', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipes', null=True, blank=True)

    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='recipes/', default='recipes/default-image.jpg')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    favorited_by = models.ManyToManyField(User, related_name='favorite_recipes', blank=True)

    ingredients = models.TextField(default='')  # Campo per la lista degli ingredienti
    instructions = models.TextField(default='')  # Campo per le istruzioni

    preparation_time = models.CharField(max_length=50, null=True, blank=True)
    cooking_time = models.CharField(max_length=50, null=True, blank=True)
    servings = models.IntegerField(null=True, blank=True)

    # Campo per la categoria
    CATEGORY_CHOICES = [
        ('Aperitivo', 'Aperitivo'),
        ('Piatto Principale', 'Piatto Principale'),
        ('Secondo Piatto', 'Secondo Piatto'),
        ('Contorno', 'Contorno'),
        ('Dessert', 'Dessert'),


    ]
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, null=True, blank=True)

    # Campo per la difficoltà
    DIFFICULTY_CHOICES = [
        ('Facile', 'Facile'),
        ('Media', 'Media'),
        ('Difficile', 'Difficile'),
    ]
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, null=True, blank=True)

    # Campo per il voto medio
    average_rating = models.FloatField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])

    def __str__(self):
        return self.title


class Comment(models.Model):
    recipe = models.ForeignKey('Recipe', related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.recipe.title}"


class Follower(models.Model):
    objects = None
    user = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)
    follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'follower')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics', null=True, blank=True)

    def __str__(self):
        return self.user.username

ffe/forms.py
from django import forms

from django.forms.widgets import PasswordInput, TextInput

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Comment, Recipe


# Create/Register User Form

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


# Authentication Form

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())


# Comment Form
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'image', 'ingredients', 'instructions', 'preparation_time', 'cooking_time',
                  'servings', 'category', 'difficulty']
        widgets = {
            'author': forms.HiddenInput(),  # Rendi il campo 'author' nascosto nel form
            'user': forms.HiddenInput(),  # Rendi il campo 'user' nascosto nel form
        }

ffe/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import CreateUserForm, LoginForm, CommentForm, ProfileForm, UserUpdateForm, RecipeForm

from .models import Recipe, Comment, Follower

# - Authentication models and functions

from django.contrib.auth.models import auth, User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash

from django.contrib.auth.decorators import login_required

from django.urls import reverse
from django.db.models import Q

from django.contrib import messages


def homepage(request):
    popular_recipes = Recipe.objects.all()[:12]  # Supponiamo che mostriamo le prime n ricette
    categories = Recipe.CATEGORY_CHOICES
    context = {
        'popular_recipes': popular_recipes,
        'categories': categories,
    }
    return render(request, "ffe/index.html", context)


def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("my-login")

    context = {"registerform": form}
    return render(request, "ffe/register.html", context=context)


def login(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect("dashboard")
            else:
                return redirect("my-login")
    else:
        form = LoginForm()

    context = {"loginform": form}
    return render(request, "ffe/login.html", context=context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Importante per mantenere l'utente loggato dopo il cambio password
            return redirect('profile')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'ffe/change_password.html', {'form': form})


@login_required(login_url="my-login")
def dashboard(request):
    followed_users = Follower.objects.filter(follower=request.user).values_list('user', flat=True)
    followed_users_list = User.objects.filter(id__in=followed_users)
    followed_recipes = Recipe.objects.filter(user__in=followed_users)
    categories = Recipe.CATEGORY_CHOICES

    # Inizializza is_following come False di default
    is_following = False

    # Se l'utente è autenticato, controlla se sta seguendo la ricetta
    if request.user.is_authenticated:
        # Qui puoi mettere la logica per determinare se l'utente segue l'utente della ricetta
        # In questo esempio, sto solo impostando is_following su True se l'utente ha almeno un follower
        is_following = Follower.objects.filter(user=request.user).exists()

    context = {
        'categories': categories,
        'followed_recipes': followed_recipes,
        'is_following': is_following,
        'followed_users': followed_users_list,
    }
    return render(request, "ffe/dashboard.html", context)


def user_logout(request):
    auth.logout(request)
    return redirect("homepage")


def explore():
    pass


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    author_username = recipe.user.username if recipe.user else None  # Ottieni l'username dell'autore della ricetta se presente
    comment_form = CommentForm()
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.user = request.user
            comment.save()
            return redirect('recipe_detail', recipe_id=recipe.id)

    is_following = False
    if request.user.is_authenticated:
        is_following = Follower.objects.filter(user=recipe.user, follower=request.user).exists()

    categories = Recipe.CATEGORY_CHOICES
    context = {
        'recipe': recipe,
        'comment_form': comment_form,
        'categories': categories,
        'is_following': is_following,
        'author_username': author_username,  # Passa l'username dell'autore della ricetta al contesto del template
    }
    return render(request, 'ffe/recipe_detail.html', context)


@login_required(login_url="my-login")
def add_comment(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.recipe = recipe
            comment.user = request.user
            comment.save()
            # Ritorna una risposta JSON di successo senza includere il messaggio "success: true"
            return JsonResponse({'success': True})
        else:
            # Se il form non è valido, ritorna una risposta JSON con gli errori del form
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = CommentForm()
    # Se la richiesta non è una richiesta POST, ritorna una risposta JSON con il messaggio di richiesta non valida
    return JsonResponse({'success': False, 'message': 'Invalid request'}, status=405)


@login_required(login_url="my-login")
def favorites(request):
    user_favorites = Recipe.objects.filter(favorited_by=request.user)
    categories = Recipe.CATEGORY_CHOICES
    context = {
        'user_favorites': user_favorites,
        'categories': categories,
    }
    return render(request, 'ffe/favorites.html', context)


@login_required(login_url="my-login")
def toggle_favorite(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if recipe.favorited_by.filter(id=request.user.id).exists():
        recipe.favorited_by.remove(request.user)
    else:
        recipe.favorited_by.add(request.user)
    return redirect('recipe_detail', recipe_id=recipe.id)


@login_required(login_url="my-login")
def remove_favorite(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if recipe.favorited_by.filter(id=request.user.id).exists():
        recipe.favorited_by.remove(request.user)
    else:
        recipe.favorited_by.add(request.user)
    return redirect('favorites')


@login_required(login_url="my-login")
def add_recipe(request):
    categories = Recipe.CATEGORY_CHOICES  # Ottieni le categorie
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user  # Imposta l'utente autenticato come autore della ricetta
            recipe.user = request.user  # Imposta l'utente autenticato come utente della ricetta
            recipe.save()
            return redirect('recipe_detail', recipe_id=recipe.id)
    else:
        initial_data = {'author': request.user, 'user': request.user}
        form = RecipeForm(initial=initial_data)  # Passa i dati iniziali al form per popolare i campi nascosti

    context = {
        'form': form,
        'categories': categories,  # Aggiungi le categorie al contesto
    }
    return render(request, 'ffe/add_recipe.html', context)


def search(request):
    query = request.GET.get('q')
    if query:
        recipes = Recipe.objects.filter(title__icontains=query)
    else:
        recipes = Recipe.objects.all()
    categories = Recipe.CATEGORY_CHOICES
    context = {
        'recipes': recipes,
        'query': query,
        'categories': categories,
    }
    return render(request, 'ffe/search_results.html', context)


def category_recipes(request, category):
    recipes = Recipe.objects.filter(category=category)
    categories = Recipe.CATEGORY_CHOICES
    context = {
        'recipes': recipes,
        'category': category,
        'categories': categories,
        'query': category  # Utilizziamo 'query' per riutilizzare lo stesso template di ricerca
    }
    return render(request, 'ffe/category_recipes.html', context)


@login_required(login_url="my-login")
def follow_user(request, username):
    # Trova l'utente da seguire
    user_to_follow = get_object_or_404(User, username=username)

    # Verifica se l'utente corrente sta già seguendo l'utente da seguire
    if Follower.objects.filter(user=user_to_follow, follower=request.user).exists():
        # Se già segue, smetti di seguire
        Follower.objects.filter(user=user_to_follow, follower=request.user).delete()
    else:
        # Altrimenti, aggiungi un nuovo follow
        Follower.objects.create(user=user_to_follow, follower=request.user)

    # Redirect alla pagina di dettaglio dell'utente seguito o a una pagina di conferma
    return redirect('user_detail', username=username)


@login_required(login_url="my-login")
def unfollow_user(request, username):
    user_to_unfollow = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        Follower.objects.filter(user=user_to_unfollow, follower=request.user).delete()
    return redirect('user_detail', username=username)


def user_detail(request, username):
    user = get_object_or_404(User, username=username)
    recipes = Recipe.objects.filter(author=user)
    is_following = Follower.objects.filter(user=user, follower=request.user).exists() if request.user.is_authenticated else False
    context = {
        'user': user,
        'recipes': recipes.distinct(),
        'num_recipes': recipes.count(),
        'is_following': is_following,
    }

ffe/templates/ffe/add_comment.html
<!DOCTYPE html>
<html lang="it-IT">
<head>
    <meta charset="UTF-8">
    <title>Aggiungi Commento</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Aggiungi un commento</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Aggiungi Commento</button>
        </form>
    </div>
</body>
</html>

ffe/templates/ffe/add_recipe.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5" style="margin: 20px">
    <h2 class="text-center">Aggiungi una nuova ricetta</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
               <div>
                    <label for="id_title" class="form-label mt-4">Titolo</label>
                    <input type="text" class="form-control" id="id_title" name="title" placeholder="Inserisci titolo">
                </div>
                <div>
                    <label for="id_description" class="form-label mt-4">Descrizione</label>
                    <textarea class="form-control" id="id_description" name="description" rows="3" placeholder="Inserisci descrizione"></textarea>
                </div>

                <div>
                    <label for="id_image" class="form-label mt-4">Immagine</label>
                    <input type="file" class="form-control" id="id_image" name="image">
                </div>
                <div>
                    <label for="id_ingredients" class="form-label mt-4">Ingredienti</label>
                    <textarea class="form-control" id="id_ingredients" name="ingredients" rows="3" placeholder="Inserisci ingredienti">{{ form.ingredients.value }}</textarea>
                </div>
                <div>
                    <label for="id_instructions" class="form-label mt-4">Istruzioni</label>
                    <textarea class="form-control" id="id_instructions" name="instructions" rows="3" placeholder="Inserisci istruzioni">{{ form.instructions.value }}</textarea>
                </div>
                <div>
                    <label for="id_preparation_time" class="form-label mt-4">Tempo di preparazione</label>
                    <input type="text" class="form-control" id="id_preparation_time" name="preparation_time" placeholder="Inserisci tempo di preparazione" value="{{ form.preparation_time.value|default_if_none:'' }}">
                </div>
                <div>
                    <label for="id_cooking_time" class="form-label mt-4">Tempo di cottura</label>
                    <input type="text" class="form-control" id="id_cooking_time" name="cooking_time" placeholder="Inserisci tempo di cottura" value="{{ form.cooking_time.value|default_if_none:'' }}">
                </div>

                <div>
                    <label for="id_servings" class="form-label mt-4">Porzioni</label>
                    <input type="number" class="form-control" id="id_servings" name="servings" placeholder="Inserisci porzioni" min="1" value="{{ form.servings.value }}">
                </div>
                <div>
                    <label for="id_category" class="form-label mt-4">Categoria</label>
                    <select class="form-select" id="id_category" name="category">
                        <option value="">Seleziona una categoria</option>
                        <option value="Aperitivo">Aperitivo</option>
                        <option value="Piatto Principale">Piatto Principale</option>
                        <option value="Secondo Piatto">Secondo Piatto</option>
                        <option value="Contorno">Contorno</option>
                        <option value="Dessert">Dessert</option>
                    </select>
                </div>
                <div>
                    <label for="id_difficulty" class="form-label mt-4">Difficoltà</label>
                    <select class="form-select" id="id_difficulty" name="difficulty">
                        <option value="">Seleziona la difficoltà</option>
                        <option value="Facile">Facile</option>
                        <option value="Media">Media</option>
                        <option value="Difficile">Difficile</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary mt-4">Salva</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}

ffe/templates/ffe/category_recipes.html
{% extends "base.html" %}

{% block extra_head %}
<style>
    /* Qui puoi mettere gli stili specifici */
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10 text-center">
            <h1>Ricette per la categoria: {{ category }}</h1>
        </div>
    </div>

    <div class="row justify-content-center" style="padding-bottom: 30px">
        {% for recipe in recipes %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{ recipe.image.url }}" class="card-img-top" alt="{{ recipe.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ recipe.title }}</h5>
                    <p class="card-text">{{ recipe.description }}</p>
                    <a href="{% url 'recipe_detail' recipe.id %}" class="btn btn-primary">Vedi ricetta</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ffe/templates/ffe/change_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Cambia la tua password</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Cambia password</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ffe/templates/ffe/dashboard.html
{% extends "base.html" %}

{% block extra_head %}
    <style>
        /* Aggiungi regole CSS personalizzate */
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .content {
            flex: 1;
        }

        .card-body {
            display: flex;
            flex-direction: column;
            height: 100%;
        }

        .description {
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 4; /* Numero di linee da mostrare */
            -webkit-box-orient: vertical;
        }

        .card-img-top {
            object-fit: cover;
            height: 300px; /* Imposta l'altezza dell'immagine */
        }

        .card {
            height: 100%; /* Imposta l'altezza della card */
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h1>Benvenuto nella tua dashboard, {{ user.username }}!</h1>
                <p>Da qui visualizzare gli utenti che segui e visualizzare le loro ricette!</p>
            </div>
        </div>
    </div>

<div class="container mt-5">
    <h2>Utenti che stai seguendo</h2>
    <ul class="list-group">
        {% if followed_users %}
            {% for followed_user in followed_users %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ followed_user.username }}
                    <form action="{% url 'user_detail' username=followed_user.username %}" method="get">
                        <button type="submit" class="btn btn-success">Vai al profilo</button>
                    </form>
                </li>
            {% endfor %}
        {% else %}
            <p>Non segui ancora nessuno.</p>
        {% endif %}
    </ul>
</div>

<div class="col-md-12">
    <div class="container mt-4">
        <h2>Ricette degli utenti che segui</h2>
        {% if followed_recipes %}
            <div class="row row-cols-1 row-cols-md-3 g-4" style="padding: 16px">
                {% for recipe in followed_recipes %}
                    <div class="col">
                        <div class="card h-100">
                            <img src="{{ recipe.image.url }}" class="card-img-top" alt="{{ recipe.title }}">
                            <div class="card-body d-flex flex-column">
                                <h6 class="card-title">Autore: <a href="{% url 'user_detail' recipe.author.username %}">{{ recipe.author.username }}</a></h6>
                                <p class="card-text flex-grow-1 description">{{ recipe.description }}</p>
                                <a href="{% url 'recipe_detail' recipe.id %}" class="btn btn-primary mt-auto">Dettagli</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>Qui è troppo vuoto... Inizia a seguire altri utenti per vedere qui le loro ricette.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

ffe/templates/ffe/edit_recipe.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5" style="margin: 20px">
    <h2 class="text-center">Modifica Ricetta</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div>
                    <label for="id_title" class="form-label mt-4">Titolo</label>
                    <input type="text" class="form-control" id="id_title" name="title" placeholder="Inserisci titolo" value="{{ form.instance.title }}">
                </div>
                <div>
                    <label for="id_description" class="form-label mt-4">Descrizione</label>
                    <textarea class="form-control" id="id_description" name="description" rows="3" placeholder="Inserisci descrizione">{{ form.instance.description }}</textarea>
                </div>

                <div>
                    <label for="id_image" class="form-label mt-4">Immagine</label>
                    {% if form.instance.image %}
                        <img src="{{ form.instance.image.url }}" alt="{{ form.instance.title }}" class="img-thumbnail" style="width: 100px; height: auto; border: none; margin-bottom: 10px;">
                    {% endif %}
                    <input type="file" class="form-control" id="id_image" name="image">
                </div>
                <div>
                    <label for="id_ingredients" class="form-label mt-4">Ingredienti</label>
                    <textarea class="form-control" id="id_ingredients" name="ingredients" rows="3" placeholder="Inserisci ingredienti">{{ form.instance.ingredients }}</textarea>
                </div>
                <div>
                    <label for="id_instructions" class="form-label mt-4">Istruzioni</label>
                    <textarea class="form-control" id="id_instructions" name="instructions" rows="3" placeholder="Inserisci istruzioni">{{ form.instance.instructions }}</textarea>
                </div>
                <div>
                    <label for="id_preparation_time" class="form-label mt-4">Tempo di preparazione</label>
                    <input type="text" class="form-control" id="id_preparation_time" name="preparation_time" placeholder="Inserisci tempo di preparazione" value="{{ form.instance.preparation_time }}">
                </div>
                <div>
                    <label for="id_cooking_time" class="form-label mt-4">Tempo di cottura</label>
                    <input type="text" class="form-control" id="id_cooking_time" name="cooking_time" placeholder="Inserisci tempo di cottura" value="{{ form.instance.cooking_time }}">
                </div>

                <div>
                    <label for="id_servings" class="form-label mt-4">Porzioni</label>
                    <input type="number" class="form-control" id="id_servings" name="servings" placeholder="Inserisci porzioni" min="1" value="{{ form.instance.servings }}">
                </div>
                <div>
                    <label for="id_category" class="form-label mt-4">Categoria</label>
                    <select class="form-select" id="id_category" name="category">
                        <option value="">Seleziona una categoria</option>
                        {% for category_value, category_label in form.fields.category.choices %}
                            <option value="{{ category_value }}" {% if category_value == form.instance.category %} selected {% endif %}>{{ category_label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <label for="id_difficulty" class="form-label mt-4">Difficoltà</label>
                    <select class="form-select" id="id_difficulty" name="difficulty">
                        <option value="">Seleziona la difficoltà</option>
                        {% for difficulty_value, difficulty_label in form.fields.difficulty.choices %}
                            <option value="{{ difficulty_value }}" {% if difficulty_value == form.instance.difficulty %} selected {% endif %}>{{ difficulty_label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary mt-4">Salva</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}